# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ModuleBCategory' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  source "https://github.com/HemingTai/HTSpecs.git"
  # Pods for ModuleBCategory
  pod 'HTScheduler'
  
end
